### ISSUE TITLE
No error returned for invalid handles

### ISSUE THREAD

**Issue by SteveFosdick** [sai2791/aund#10]
When sending a request on an (supposedly) open file with an invalid file handle there is a check to make sure the handle is valid, for example in fs_getbyte:
```
    if ((h = fs_check_handle(c->client, request->handle)) != 0) {
```
But if this test fails no error is sent.  I believe this should be sending back the "Channel" error, i.e. the else part should be:
```
    else
        fs_err(c, EC_FS_E_CHANNEL);
```
This applies to gs_getbyte, fs_getbytes, fs_putbyte, fs_putbytes.

**Comment by sai2791** [comment]
Fixed by Pull Request #12
