### ISSUE TITLE
Building refers to files in your home directory

### ISSUE THREAD

**Issue by SteveFosdick** [sai2791/aund#13]
./configure runs fine but when I type make it refers to a file 'documents/aund/missing' under your home directory which is therefore not in the package as cloned, or part of a standard Linux install.

**Comment by sai2791** [comment]
let me take a look at that, I do remember having to use automake --add-missing but I will check

**Comment by sai2791** [comment]
Did you run sh ./bootstrap.sh from the build directory, it should do all of this stuff for you.

**Comment by sai2791** [comment]
Updated documentation to include reference to the ./bootscript.sh prior to running the ./configure script

**Comment by SteveFosdick** [comment]
Just for reference, bootstrap.sh gives some warnings:
```
configure.ac:37: installing './ar-lib'
configure.ac:33: warning: The macro `AC_PROG_CC_C99' is obsolete.
configure.ac:33: You should run autoupdate.
./lib/autoconf/c.m4:1659: AC_PROG_CC_C99 is expanded from...
configure.ac:33: the top level
configure.ac:36: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
aclocal.m4:710: AM_PROG_LEX is expanded from...
configure.ac:36: the top level
```

Other than that running ./bootstrap.sh then ./configure then make does generate an executable.  There are also some compiler warnings.

**Comment by sai2791** [comment]
I've pushed some changes to remove the warnings for the AC_PROG_CC_C99 and AC_PROG_LEX.  I need to check if I also need to update the required autoconf to 2.69, apparently lots of stuff has been depreciated or changed.

**Comment by sai2791** [comment]
The compiler warnings are differences between clang which isn't showing them and gcc 10.2 which is.  Will check these next but hopefully it may just need #ifdefs
