### ISSUE TITLE
AUND allows the creation of a directory over an existing file

### ISSUE THREAD

**Issue by sai2791** [sai2791/aund#16]
The user can create a directory with the same name as an existing file

**Comment by SteveFosdick** [comment]
Be careful here.  I assume this comes from the OSFILE test program which was written to check compatibility with the full filing system API.  From the 8bit days, ADFS supports all the OSFILE functions but DFS does not and this may be one of them.  I'd check that the request is being sent to aund before considering this a bug.

**Comment by sai2791** [comment]
Checked on a master and bbc b both error with file exists, so it does look like this is ok and I will close this issue.
