### ISSUE TITLE
Attemping *. when not logged in goes into a timeout loop

### ISSUE THREAD

**Issue by SteveFosdick** [sai2791/aund#4]
Beware, this might be an emulator bug but running*. on B-Em I get this from aund:
```
started as fileserver at station [254]

	(file server: {&=0,@=0,%=0} fs_error: 0xbf/Who are you?
aund: Tx reply: Connection timed out
)

	(file server: {&=0,@=0,%=0} fs_error: 0xbf/Who are you?
aund: Tx reply: Connection timed out
)

	(file server: {&=0,@=0,%=0} fs_error: 0xbf/Who are you?
aund: Tx reply: Connection timed out
```

**Comment by sai2791** [comment]
I've check this, and the aund server is trying to reply and is not receiving an acknowledgement. I've also checked the B-Em version 2.2 which has a readme that says Econet is not implemented yet.  Do you have a later version, V2.2 is dated the 3rd June 2012

**Comment by SteveFosdick** [comment]
Thanks, I think this was because both B-Em and aund were running on the same host.  aund was on port 32768 and B-Em was on some other port.  So aund was replying to port 32768, and thus to itself, rather than to B-Em.

For B-Em, v2.2 is the last formal release but there is a much more recent version at: https://github.com/stardot/b-em

Even that doesn't have the Econet code as I only started porting it (from BeebEm) this week. I am hoping to push a branch soon.

**Comment by sai2791** [comment]
This was apparently a client issue, which has now been fixed
