### ISSUE TITLE
The "null" user management option has missing methods, results in coredump.

### ISSUE THREAD

**Issue by SteveFosdick** [sai2791/aund#5]
When running with the null user managment option, which seems to be the default with the supplied example config file, logging on (*I AM) causes a segmentation fault when trying to invoke:
```
c->client->priv = userfuncs->get_priv(c->client->login);
```
in fs_cmd_i_am in fs_cli.c.  This is because this method, and several others, are not defined for this user option which has:
```
struct user_funcs const user_null = {
	null_validate, null_urd, null_change, null_set_opt4
};
```
compared with:
```
struct user_funcs const user_pw = {
	pw_validate, pw_urd, pw_change, pw_set_opt4, pw_set_priv, pw_get_priv,
    pw_add_user, pw_is_user, pw_del_user

};
```
in pw.c

**Comment by sai2791** [comment]
Fixed to include all of the missing null versions of the user functions.

The code has been pushed to the master branch
